import {
  Product,
  Sale,
  Expense,
  Customer,
  Supplier,
  Purchase,
  InventoryAdjustment,
  BusinessSettings,
  AuditLog,
  NotificationItem,
  ProductCategory
} from '../types';

const STORAGE_KEYS = {
  PRODUCTS: 'glow_erp_products',
  SALES: 'glow_erp_sales',
  EXPENSES: 'glow_erp_expenses',
  CUSTOMERS: 'glow_erp_customers',
  SUPPLIERS: 'glow_erp_suppliers',
  PURCHASES: 'glow_erp_purchases',
  INVENTORY_LOGS: 'glow_erp_inventory_logs',
  SETTINGS: 'glow_erp_settings',
  AUDIT_LOGS: 'glow_erp_audit_logs',
  NOTIFICATIONS: 'glow_erp_notifications',
  OFFLINE_QUEUE: 'glow_erp_offline_queue',
};

export const DEFAULT_CATEGORIES: ProductCategory[] = [
  { id: 'cat-1', name: 'Makeup', color: '#ec4899' },
  { id: 'cat-2', name: 'Lipstick', color: '#ef4444' },
  { id: 'cat-3', name: 'Powder', color: '#f59e0b' },
  { id: 'cat-4', name: 'Foundation', color: '#d97706' },
  { id: 'cat-5', name: 'Cream', color: '#10b981' },
  { id: 'cat-6', name: 'Lotion', color: '#06b6d4' },
  { id: 'cat-7', name: 'Perfume', color: '#8b5cf6' },
  { id: 'cat-8', name: 'Hair Products', color: '#6366f1' },
  { id: 'cat-9', name: 'Soap', color: '#14b8a6' },
  { id: 'cat-10', name: 'Skincare', color: '#f43f5e' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-101',
    name: 'Matte Velvet Lipstick #05 Velvet Red',
    barcode: '89301234001',
    sku: 'LIP-MAT-05',
    category: 'Lipstick',
    brand: 'GlowGlam',
    costPrice: 2500,
    sellingPrice: 4500,
    wholesalePrice: 3800,
    currentStock: 35,
    reorderLevel: 10,
    supplierId: 'sup-1',
    supplierName: 'Afriluxe Beauty Depot',
    dateCreated: '2026-07-01',
    imageUrl: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod-102',
    name: 'Full Coverage HD Foundation Warm Honey',
    barcode: '89301234002',
    sku: 'FND-HD-02',
    category: 'Foundation',
    brand: 'Fenty Radiance',
    costPrice: 6000,
    sellingPrice: 11500,
    wholesalePrice: 9800,
    currentStock: 18,
    reorderLevel: 5,
    supplierId: 'sup-1',
    supplierName: 'Afriluxe Beauty Depot',
    dateCreated: '2026-07-02',
    imageUrl: 'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod-103',
    name: 'Vitamin C Brightening Face Serum 30ml',
    barcode: '89301234003',
    sku: 'SKN-VITC-30',
    category: 'Skincare',
    brand: 'Pure Essence',
    costPrice: 4200,
    sellingPrice: 8000,
    wholesalePrice: 7000,
    currentStock: 4, // Low stock on purpose
    reorderLevel: 8,
    supplierId: 'sup-2',
    supplierName: 'DermaCare Imports Ltd',
    dateCreated: '2026-07-03',
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod-104',
    name: 'Cocoa Butter Hydrating Body Lotion 500ml',
    barcode: '89301234004',
    sku: 'LOT-COCO-500',
    category: 'Lotion',
    brand: 'SatinSkin',
    costPrice: 3000,
    sellingPrice: 5500,
    wholesalePrice: 4800,
    currentStock: 50,
    reorderLevel: 12,
    supplierId: 'sup-2',
    supplierName: 'DermaCare Imports Ltd',
    dateCreated: '2026-07-04',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod-105',
    name: 'Midnight Amber Eau de Parfum 100ml',
    barcode: '89301234005',
    sku: 'PRF-AMB-100',
    category: 'Perfume',
    brand: 'Oud Royal',
    costPrice: 18000,
    sellingPrice: 32000,
    wholesalePrice: 27000,
    currentStock: 8,
    reorderLevel: 3,
    supplierId: 'sup-3',
    supplierName: 'Fragrance World Nig',
    dateCreated: '2026-07-05',
    imageUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod-106',
    name: 'Compact Pressed Powder Oil Control Caramel',
    barcode: '89301234006',
    sku: 'PWD-CMP-03',
    category: 'Powder',
    brand: 'GlowGlam',
    costPrice: 2200,
    sellingPrice: 4000,
    wholesalePrice: 3400,
    currentStock: 22,
    reorderLevel: 6,
    supplierId: 'sup-1',
    supplierName: 'Afriluxe Beauty Depot',
    dateCreated: '2026-07-06',
  },
  {
    id: 'prod-107',
    name: 'Argan Oil Deep Conditioning Hair Treatment',
    barcode: '89301234007',
    sku: 'HAR-ARG-250',
    category: 'Hair Products',
    brand: 'Silk Crown',
    costPrice: 3500,
    sellingPrice: 6500,
    wholesalePrice: 5600,
    currentStock: 2, // Low stock
    reorderLevel: 10,
    supplierId: 'sup-2',
    supplierName: 'DermaCare Imports Ltd',
    dateCreated: '2026-07-07',
  },
  {
    id: 'prod-108',
    name: 'African Black Soap Turmeric Glowing Bar',
    barcode: '89301234008',
    sku: 'SOP-BLK-TUR',
    category: 'Soap',
    brand: 'Natures Glow',
    costPrice: 1200,
    sellingPrice: 2500,
    wholesalePrice: 2000,
    currentStock: 65,
    reorderLevel: 15,
    supplierId: 'sup-2',
    supplierName: 'DermaCare Imports Ltd',
    dateCreated: '2026-07-08',
  }
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Mrs. Amina Bello',
    phone: '08031234567',
    email: 'amina.bello@example.com',
    totalPurchases: 145000,
    outstandingDebt: 12500, // Has a debt
    lastPurchaseDate: '2026-07-28',
  },
  {
    id: 'cust-2',
    name: 'Blessing Okonkwo',
    phone: '08129876543',
    email: 'blessing.o@example.com',
    totalPurchases: 82000,
    outstandingDebt: 0,
    lastPurchaseDate: '2026-07-27',
  },
  {
    id: 'cust-3',
    name: 'Glam Studio Spa (Anita)',
    phone: '07055512345',
    totalPurchases: 320000,
    outstandingDebt: 45000,
    lastPurchaseDate: '2026-07-26',
  }
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    name: 'Afriluxe Beauty Depot',
    phone: '08022223333',
    email: 'orders@afriluxe.com',
    address: 'Suite 14, Trade Fair Complex, Lagos',
    productsSupplied: ['Lipstick', 'Foundation', 'Powder', 'Makeup'],
    outstandingBalance: 65000,
  },
  {
    id: 'sup-2',
    name: 'DermaCare Imports Ltd',
    phone: '08134445555',
    email: 'sales@dermacare.ng',
    address: '45 Allen Avenue, Ikeja, Lagos',
    productsSupplied: ['Skincare', 'Lotion', 'Soap', 'Hair Products'],
    outstandingBalance: 0,
  },
  {
    id: 'sup-3',
    name: 'Fragrance World Nig',
    phone: '07089990000',
    email: 'info@fragranceworld.ng',
    address: 'Plaza 8, Balogun Market, Lagos Island',
    productsSupplied: ['Perfume'],
    outstandingBalance: 120000,
  }
];

export const INITIAL_SETTINGS: BusinessSettings = {
  businessName: 'Glow Beauty Cosmetics Store',
  logoUrl: '',
  address: 'Plot 12 Admiralty Way, Lekki Phase 1, Lagos',
  phone: '+234 803 888 9900',
  alternatePhone: '+234 802 111 2233',
  email: 'hello@glowbeauty.ng',
  website: 'https://glowbeauty.ng',
  city: 'Lekki',
  state: 'Lagos',
  country: 'Nigeria',
  enableTax: false,
  taxName: 'VAT',
  taxRate: 7.5, // 7.5% VAT
  displayTaxOnReceipt: false,
  currencySymbol: '₦',
  currencyCode: 'NGN',
  receiptHeader: 'Glow Beauty Cosmetics Store - Quality Beauty & Skincare Depot',
  receiptFooter: 'Thank you for shopping at Glow Beauty! Items purchased in good condition are non-refundable after 3 days.',
  enableDarkMode: false,
  autoBackupCloud: true,
  lastBackupTime: new Date().toISOString(),
};

export const DEFAULT_EXPENSE_CATEGORIES = [
  'Rent',
  'Salaries & Wages',
  'Staff Welfare',
  'Electricity',
  'Generator Fuel',
  'Internet',
  'Transportation',
  'Packaging Materials',
  'Shop Maintenance',
  'Cleaning',
  'Office Supplies',
  'Advertising & Marketing',
  'Logistics & Delivery',
  'Inventory Purchases',
  'Equipment',
  'Repairs & Maintenance',
  'Bank Charges',
  'POS Charges',
  'Loan Repayment',
  'Security',
  'Water',
  'Taxes & Levies',
  'Miscellaneous',
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    date: new Date().toISOString().split('T')[0],
    timestamp: new Date().toISOString(),
    category: 'Transportation',
    description: 'Dispatch delivery for VIP order to Ikeja',
    amount: 3500,
    paidBy: 'Cash',
    paymentMethod: 'cash',
    vendor: 'Gokada Express Logistics',
    branch: 'Main Branch',
    notes: 'Waybill #GK-88219',
    status: 'paid',
  },
  {
    id: 'exp-2',
    date: new Date().toISOString().split('T')[0],
    timestamp: new Date().toISOString(),
    category: 'Generator Fuel',
    description: 'Diesel purchase for store generator (20 Litres)',
    amount: 14000,
    paidBy: 'Transfer',
    paymentMethod: 'transfer',
    vendor: 'TotalEnergies Station Lekki',
    branch: 'Main Branch',
    notes: 'Bought at ₦700/Litre',
    status: 'paid',
  },
  {
    id: 'exp-3',
    date: '2026-07-27',
    timestamp: '2026-07-27T10:30:00Z',
    category: 'Packaging Materials',
    description: 'Branded gift bags and bubble wrap rolls',
    amount: 8500,
    paidBy: 'POS',
    paymentMethod: 'pos',
    vendor: 'Lagos Pack Co.',
    branch: 'Main Branch',
    notes: '500 custom pink cosmetic bags',
    status: 'paid',
  },
  {
    id: 'exp-4',
    date: '2026-07-20',
    timestamp: '2026-07-20T09:00:00Z',
    category: 'Salaries & Wages',
    description: 'Bi-weekly sales representative stipend',
    amount: 45000,
    paidBy: 'Transfer',
    paymentMethod: 'transfer',
    vendor: 'Chioma Okeke (Sales Representative)',
    branch: 'Main Branch',
    notes: 'Staff salary payment',
    status: 'paid',
  },
  {
    id: 'exp-5',
    date: '2026-07-01',
    timestamp: '2026-07-01T08:00:00Z',
    category: 'Rent',
    description: 'Monthly store shop rent allocation',
    amount: 150000,
    paidBy: 'Transfer',
    paymentMethod: 'transfer',
    vendor: 'Admiralty Shopping Plaza Landlord',
    branch: 'Main Branch',
    notes: 'Shop #12 monthly rent',
    status: 'paid',
  }
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'sale-1',
    invoiceNumber: 'INV-1001',
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
    date: new Date().toISOString().split('T')[0],
    items: [
      {
        productId: 'prod-101',
        productName: 'Matte Velvet Lipstick #05 Velvet Red',
        quantity: 2,
        unitCost: 2500,
        unitPrice: 4500,
        discount: 0,
        subtotal: 9000,
        category: 'Lipstick'
      },
      {
        productId: 'prod-106',
        productName: 'Compact Pressed Powder Oil Control Caramel',
        quantity: 1,
        unitCost: 2200,
        unitPrice: 4000,
        discount: 500,
        subtotal: 3500,
        category: 'Powder'
      }
    ],
    subtotal: 13000,
    discount: 500,
    tax: 0,
    totalAmount: 12500,
    costOfGoodsSold: 7200,
    grossProfit: 5300,
    amountPaid: 12500,
    changeGiven: 0,
    outstandingDebt: 0,
    customerName: 'Blessing Okonkwo',
    customerPhone: '08129876543',
    customerId: 'cust-2',
    paymentMethod: 'transfer',
    salespersonRole: 'salesperson',
    salespersonName: 'Chioma (Sales)',
    isSynced: true,
  },
  {
    id: 'sale-2',
    invoiceNumber: 'INV-1002',
    timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
    date: new Date().toISOString().split('T')[0],
    items: [
      {
        productId: 'prod-105',
        productName: 'Midnight Amber Eau de Parfum 100ml',
        quantity: 1,
        unitCost: 18000,
        unitPrice: 32000,
        discount: 0,
        subtotal: 32000,
        category: 'Perfume'
      }
    ],
    subtotal: 32000,
    discount: 0,
    tax: 0,
    totalAmount: 32000,
    costOfGoodsSold: 18000,
    grossProfit: 14000,
    amountPaid: 32000,
    changeGiven: 0,
    outstandingDebt: 0,
    customerName: 'Walk-in Customer',
    paymentMethod: 'pos',
    salespersonRole: 'salesperson',
    salespersonName: 'Chioma (Sales)',
    isSynced: true,
  },
  {
    id: 'sale-3',
    invoiceNumber: 'INV-1003',
    timestamp: '2026-07-27T14:20:00Z',
    date: '2026-07-27',
    items: [
      {
        productId: 'prod-102',
        productName: 'Full Coverage HD Foundation Warm Honey',
        quantity: 2,
        unitCost: 6000,
        unitPrice: 11500,
        discount: 1000,
        subtotal: 22000,
        category: 'Foundation'
      }
    ],
    subtotal: 23000,
    discount: 1000,
    tax: 0,
    totalAmount: 22000,
    costOfGoodsSold: 12000,
    grossProfit: 10000,
    amountPaid: 22000,
    changeGiven: 0,
    outstandingDebt: 0,
    customerName: 'Mrs. Amina Bello',
    customerPhone: '08031234567',
    customerId: 'cust-1',
    paymentMethod: 'cash',
    salespersonRole: 'manager',
    salespersonName: 'Store Manager',
    isSynced: true,
  }
];

export const loadFromStorage = <T>(key: string, fallback: T): T => {
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return fallback;
    return JSON.parse(raw);
  } catch (err) {
    console.error(`Error loading key ${key}:`, err);
    return fallback;
  }
};

export const saveToStorage = <T>(key: string, data: T): void => {
  try {
    localStorage.setItem(key, JSON.stringify(data));
  } catch (err) {
    console.error(`Error saving key ${key}:`, err);
  }
};
